# Generated by Django 4.1 on 2023-01-26 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория аты')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=200, verbose_name='Тегі')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тұтынушы',
                'verbose_name_plural': 'Тұтынушылар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тауар аты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Бағасы')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Сурет')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тауар',
                'verbose_name_plural': 'Тауарлар',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Саны')),
                ('data_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Тапысырыс күні')),
                ('complete', models.BooleanField(default=False, verbose_name='Орындалды/Орындалмады')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer', verbose_name='Тұтынушы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Тауар')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыстар',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Саны')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Тапсырыс')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Тауар')),
            ],
            options={
                'verbose_name': 'Себет',
                'verbose_name_plural': 'Себет',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон №')),
                ('street', models.CharField(max_length=30, verbose_name='Көше')),
                ('home_number', models.IntegerField(verbose_name='Үй №')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж №')),
                ('door', models.IntegerField(blank=True, null=True, verbose_name='Пәтер №')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer', verbose_name='Тұтынушы')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Тапсырыс')),
            ],
            options={
                'verbose_name': 'Мекен-жай',
                'verbose_name_plural': 'Мекен-жай',
            },
        ),
    ]
