# Generated by Django 4.1 on 2023-01-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_order_alter_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Саны')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='Тапсырыс')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Тауар')),
            ],
            options={
                'verbose_name': 'Тапсырыс орны',
                'verbose_name_plural': 'Тапсырыс орны',
            },
        ),
    ]
