# Generated by Django 4.1 on 2023-01-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
